// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBm8BYw-AHNUCkTskIrIKROSgsSmi8aWY',
    appId: '1:267790795234:web:c3edefcc21f31f68ddb9bb',
    messagingSenderId: '267790795234',
    projectId: 'sincheol-flutter-project1',
    authDomain: 'sincheol-flutter-project1.firebaseapp.com',
    databaseURL: 'https://sincheol-flutter-project1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sincheol-flutter-project1.appspot.com',
    measurementId: 'G-Z69GF6QNB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1aZXWiF9lHY4hlcxhEnlb5AIEQNmlQhI',
    appId: '1:267790795234:android:459bd4198f058509ddb9bb',
    messagingSenderId: '267790795234',
    projectId: 'sincheol-flutter-project1',
    databaseURL: 'https://sincheol-flutter-project1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sincheol-flutter-project1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0tCG4rmlRmAYF2a3jSLMVGongu8RQCsI',
    appId: '1:267790795234:ios:ec6c19cc40860d62ddb9bb',
    messagingSenderId: '267790795234',
    projectId: 'sincheol-flutter-project1',
    databaseURL: 'https://sincheol-flutter-project1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sincheol-flutter-project1.appspot.com',
    iosClientId: '267790795234-p1bauj4gtueeqq9pd6hu0tlmh1tb0q99.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0tCG4rmlRmAYF2a3jSLMVGongu8RQCsI',
    appId: '1:267790795234:ios:ec6c19cc40860d62ddb9bb',
    messagingSenderId: '267790795234',
    projectId: 'sincheol-flutter-project1',
    databaseURL: 'https://sincheol-flutter-project1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sincheol-flutter-project1.appspot.com',
    iosClientId: '267790795234-p1bauj4gtueeqq9pd6hu0tlmh1tb0q99.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );
}
